/* Theme */
export const CHANGE_THEME = 'CHANGE_THEME';
/* Theme */

/* FilterConfigurator */
export const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_FAILURE = 'FETCH_RATES_FAILURE';

export const RETRIEVE_REQUEST = 'RETRIEVE_REQUEST ';
export const RETRIEVE_SUCCESS = 'RETRIEVE_SUCCESS';
export const RETRIEVE_FAILURE = 'RETRIEVE_FAILURE';
/* FilterConfigurator */

/* History */
export const FETCH_CONVERSIONS_REQUEST = 'FETCH_CONVERSIONS_REQUEST';
export const FETCH_CONVERSIONS_SUCCESS = 'FETCH_CONVERSIONS_SUCCESS';
export const FETCH_CONVERSIONS_FAILURE = 'FETCH_CONVERSIONS_FAILURE';
/* History */
